name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: production pdf
      run: |
        apt-get install latexmk
        cd poly/sources
        make
